[package]
name = "custom"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = "1.35"
tracing-subscriber = "0.3"
# z4-engine = "0.0.1"
z4-engine = { path = "../../z4/engine" }
